.TH "Gambas" "1" "October 2013" "Ubuntu" ""

.SH "NAME"
gambas3 \- Integrated Development Environment

.SH "SYNOPSIS"
.B gambas3
[options] [<project directory>]

.SH "DESCRIPTION"
Gambas is, before all, a Basic language with object extensions.
A program written with Gambas is a set of files. Each file describes
a class, in terms of object programming. The class files are compiled,
then executed by an interpreter. From this point of view, it is
very inspired by Java.

Gambas is made up of the following programs:

    * A compiler.
    * An interpreter.
    * An archiver.
    * A graphical user interface component.
    * A development environment.

The development environment is written with Gambas itself, so that you can
see the abilities of the language.

\fBgambas3\fR starts the Integrated Development Environment.

.SH "OPTIONS"
.TP
\fB\-V, --version\fR
display version
.TP
\fB\-L, --license\fR
display license
.TP
\fB\-h, --help\fR
display help and exit

.SH "AVAILABILITY"
The latest version of Gambas can always be obtained from
\fBgambas.sourceforge.net\fR, documentation about the language is at
\fBhttp://gambaswiki.org/wiki\fR.

.SH "REPORTING BUGS"
Report bugs to \fBhttp://gambaswiki.org/bugtracker\fR

.SH "COPYRIGHT"
Copyright\(co Benoît Minisini <g4mba5@gmail.com>;
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
