' Gambas module file

Public Sub Main()

    ' These must succeed:
    
    'Test

    Test.Main("TestAllAsserts", Null)
    Test.Main("TestSetup", Null)
    Test.Main("TestElse", Null)
    Test.Main("TestError", Null)
    Test.Main("TestSetupTeardown", Null)

    ' Here every test must fail:
    ' Test.Main("TestFailures", Null)
    ' Test.Main("TestBailout", Null)

    'This will BailOut
    ' Test.Main("TestEmpty", Null)

    'Test all
    'Test.Main(Null, Null)

    ' Just one test
    Test.Main("TestAllAsserts", "TestAssert")

    'Cheese()

End

Private Sub (Cheese)()

End
