' Gambas module file

Public Sub Main()

    ' These must succeed:

    UnitTest.Main("TestAllAsserts", Null)
    UnitTest.Main("TestSetup", Null)
    UnitTest.Main("TestElse", Null)
    UnitTest.Main("TestError", Null)
    UnitTest.Main("TestSetupTeardown", Null)

    ' Here every test must fail:
    UnitTest.Main("TestFailures", Null)
    UnitTest.Main("TestBailout", Null)

    'This will BailOut
    UnitTest.Main("TestEmpty", Null)

    'Test all
    'UnitTest.Main(Null, Null)

    ' Just one test
    UnitTest.Main("TestAllAsserts", "TestAssert")

    'Cheese()

End

Private Sub (Cheese)()

End
