' Gambas module file

Public Sub Main()

    ' These must succeed:
    ' UnitTest.Main("TestAllAsserts", Null, True)
    ' UnitTest.Main("TestSetup", Null, True)
    ' UnitTest.Main("TestElse", Null, True)
    ' UnitTest.Main("TestError", Null, True)
    ' UnitTest.Main("TestSetupTeardown", Null, True)

    ' Here every test must fail:
    'UnitTest.Main("TestFailures", Null, True)

    'Test all
    UnitTest.Main(Null, Null, True)

End
