' Gambas module file

''' Keeps track of test counts and result(s)

'' Current Test Container
Public ContainerName As String

'' Current Test Method
Public TestName As String

'' Number of Tests done inside a TestMethod.
'' Is printed if no message was given at the assert.
Public MethodTestsCount As Integer

'' Counts Asserts done inside a TestContainer.
Public ContainerTestsCount As Integer

'' Counts all Asserts done
Public Counter As Long

'' Planned Asserts count
Public Plan As Long

'' Counts Not Ok
Public NOKs As New Long[]
'' Counts Ok
Public OKs As New Long[]


Public Sub Reset()

    ContainerName = Null
    TestName = Null
    MethodTestsCount = 0
    ContainerTestsCount = 0
    Counter = 0
    Plan = 0
    NOKs.Clear
    Oks.Clear

End
