' Gambas module file

' Play around for development ...


Public Sub Main()

    ' ------------------------------------------------- Interpreter Interface
    ' Dim testclass As Class
    ' 
    ' testclass = Class.Load("TestElse")
    ' Test._Add(testclass, "TestElse.TestNote")
    ' testclass = Class.Load("TestAllAsserts")
    ' Test._Add(testclass, "TestAllAsserts")
    ' ' these are already contained, do not increase the numbers of tests!
    ' Test._Add(testclass, "TestAllAsserts.TestNote;TestLike")
    ' 
    ' Test._Run()

End
