' Gambas module file

' Playground for development ...


Public Sub Main()

    ' ------------------------------------------------- Interpreter Interface

    Dim Ass As Class
    Dim name As String
    Dim Symbols As String[]
    
    Ass = Class.Load("Assert")
    
    Symbols = Ass.Symbols
    Symbols.Sort
    
    For Each Name In Symbols
        Print "Public Sub " & Name & "()" & gb.lf & "End"
    Next

End
